apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: skills-eks-cluster
 region: us-east-1

vpc:
 clusterEndpoints:
   publicAccess:  true
   privateAccess: true

nodeGroups:
 - name: ng-1
   instanceType: t2.small
   desiredCapacity: 2