apiVersion: v1
kind: Deployment
metadata:
  name: es
  labels:
    app: es

spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: elasticsearch